### PR TITLE
Fix: BUG#348 Parameter change detection fix when path doesn't change but PathParams AND Parameters are changed (But named the same)

### PR DESCRIPTION
**Pull request by mishukdutta-toast**
* When endpoint pathParams change and Parameter names are changed to be similar to pathParams
  - Don't remove parameters from the path 
  - This allows the `ChangedParameter class` to not lose parameters and `detect/return` changes    

Fixes: #353 
```
OperationsDiff.java:
removePathParameters(context.getParameters(), params);
```
removes Parameters which are marked - in: path

So changes to the schema for those parameters are not detected anymore when
`.getParametersDiff().diff(...` is run after removal

### CODE REVIEW

**Comment by mishukdutta-toast** [comment]
fixes #353 
```
OperationsDiff.java:
removePathParameters(context.getParameters(), params);`
```
removes Parameters which are marked  `- in: path` 
So changes to the schema for those parameters are not detected anymore when 
`.getParametersDiff().diff(...` is  run after removal

**Comment by mishukdutta-toast** [comment]
tagging @joschi for visibility

**Comment by mishukdutta-toast** [comment]
tagging @joschi for visibility

**Review by joschi — APPROVED** [review]
@mishukdutta-toast Thanks for your contribution! ❤️

**Pull request merged**
